# Use postgres/example user/password credentials
version: '3.6'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 8000:8000 # server container
      - 8001:8001
    volumes:
      - "./frontend/src:/app"

  api:
    build: 
      context: ./api
      dockerfile: backend.dockerfile
    volumes:
      - "./api/src:/src"
    ports:
      - 8081:8081
